"""
Label derivation for the multi-head contact/lift/success critic (C.3).

Naming discipline (per results/risk_gated_vla/LITERATURE_AND_NOVELTY_PLAN.md's
B.5 and this experiment's own scoping decision): this module backs a
"multi-head contact/lift/success critic" -- NOT a retention critic, NOT a
world model. See DATA_AUDIT.md (generated by scripts/audit_multihead_labels.py)
for the empirical basis of every scoping decision encoded below.

Two labels are DIAGNOSTIC ONLY, not training targets, per explicit user
decision (2026-07-30):

  - retained_grasp_proxy: perfectly collinear with bilateral_contact in every
    currently-collected split (weld only triggers on bilateral contact, per
    tango_robot/env_soarm.py's fixed weld gate). Not included in any loss
    term, AUROC/AUPRC, or main-result table. If this project ever re-executes
    the environment to record a genuine post-settle retention check (distinct
    from the weld-attach signal), THAT should become the real
    retained_grasp label -- this proxy must not be cited as equivalent to it.
  - failure_type's full 6-class taxonomy is a documented future schema, not
    the current training target. Only 3 classes are realized in every
    currently-collected split (success / no_contact / weld_no_lift);
    contact_no_weld, lifted_then_dropped, and other_or_inconsistent are
    STRUCTURALLY unreachable given the current weld gate (identical to
    bilateral_contact) and the current fell_off threshold (never triggers
    within the 40-step post-grasp settle window). failure_type_3class() below
    fails loudly (UnrealizedFailureTypeError) rather than silently if a
    candidate ever maps to one of the three excluded classes -- this must not
    be caught and ignored; it means the data-generating process changed and
    the training scope needs to be revisited, not silently expanded.
"""
from __future__ import annotations

FAILURE_TYPES_REALIZED = ("success", "no_contact", "weld_no_lift")
FAILURE_TYPES_FUTURE_SCHEMA = FAILURE_TYPES_REALIZED + (
    "contact_no_weld", "lifted_then_dropped", "other_or_inconsistent",
)

_REQUIRED_FIELDS = ("lifted", "weld_triggered", "fell_off", "bilateral_contact")


class UnrealizedFailureTypeError(ValueError):
    """Raised when a candidate maps to one of the three failure_type classes
    confirmed to have zero samples across every collected split as of the
    2026-07-30 audit (see DATA_AUDIT.md). This means the data-generating
    process (grasp primitive, fell_off threshold, weld gate) has changed
    since that audit -- the fix is to re-run the audit and revisit the
    3-class training scope, not to catch and discard this exception."""


def _check_fields(cand: dict) -> None:
    missing = [f for f in _REQUIRED_FIELDS if f not in cand]
    if missing:
        raise KeyError(f"candidate missing required field(s) {missing}: {cand!r}")


def derive_success(cand: dict) -> bool:
    """success = lifted AND retained_grasp_proxy(=weld_triggered) AND NOT fell_off.
    Confirmed (DATA_AUDIT.md) to match the recorded `success` field exactly,
    0 mismatches across all 3600 candidates in train-100/dev-200/confirm-300."""
    _check_fields(cand)
    return bool(cand["lifted"] and cand["weld_triggered"] and not cand["fell_off"])


def derive_dropped_after_lift(cand: dict) -> bool:
    """lifted AND fell_off. Confirmed structurally unreachable in current data
    (fell_off is always False) -- kept as documented future schema only."""
    _check_fields(cand)
    return bool(cand["lifted"] and cand["fell_off"])


def derive_retained_grasp_proxy(cand: dict) -> bool:
    """DIAGNOSTIC ALIAS ONLY -- see module docstring. Currently identical to
    bilateral_contact for every collected candidate. Do not train on this as
    an independent target; do not cite as evidence of post-settle retention."""
    _check_fields(cand)
    return bool(cand["weld_triggered"])


def failure_type_full6(cand: dict) -> str:
    """Full 6-class taxonomy per the confirmed priority rule. Documented
    future schema -- NOT the current training target, see failure_type_3class()."""
    _check_fields(cand)
    if derive_success(cand):
        return "success"
    if not cand["bilateral_contact"]:
        return "no_contact"
    if cand["bilateral_contact"] and not cand["weld_triggered"]:
        return "contact_no_weld"
    if cand["weld_triggered"] and not cand["lifted"]:
        return "weld_no_lift"
    if derive_dropped_after_lift(cand):
        return "lifted_then_dropped"
    return "other_or_inconsistent"


def failure_type_3class(cand: dict) -> str:
    """The actual training target for this round: realized-class-only
    (success / no_contact / weld_no_lift). Fails loudly, does not silently
    clip, if a candidate maps to one of the three currently-unrealized
    classes -- see UnrealizedFailureTypeError."""
    ft = failure_type_full6(cand)
    if ft not in FAILURE_TYPES_REALIZED:
        raise UnrealizedFailureTypeError(
            f"candidate mapped to failure_type={ft!r}, confirmed to have zero "
            f"samples across every collected split as of the 2026-07-30 audit "
            f"(see DATA_AUDIT.md) -- do not catch this and fall back silently. "
            f"candidate={cand!r}"
        )
    return ft
