#!/usr/bin/env python3
"""
Geometry-Conditioned Energy-Based grasp candidate scorer.

Direct descendant of train_ebm_grasp.py (v2, InfoNCE with self-mined
adversarial negatives -- that training RECIPE is unchanged and already
validated: it fixed v1's catastrophic CEM-exploit failure). The one change:
the energy function's input is the 6-dim "live-computable" object-relative
geometric/affordance feature subset (width, H, local_point_density,
normal_consistency, contact_width_ratio, pe_ik) instead of raw world-frame
pose (x, y, sin(yaw), cos(yaw)).

Motivation (2026-07-12 session): a systematic diagnostic this session found
that raw pose carries near-chance success signal for several objects
(scene-grouped-CV AUC: Pear 0.511, Mustard 0.582, Can 0.498 -- confirmed
NOT an artifact of row-level train/test leakage, verified via GroupKFold
grouped by scene_id), while the existing 12-dim LGGSN-style geometric
feature set carries strong signal (Pear 0.901, Mustard 0.876, Can 0.825).
EBM v2 (this file's ancestor) scores raw pose -- exactly the weak
representation -- which plausibly explains why it only ties baseline
(74.0% vs 77.7%, p=0.29) rather than clearly beating it, despite having the
right (hard-negative-mining) training recipe. A 6-dim subset of the 12
(dropping episode-batch-relative dist_to_centroid/z_rel and the
execution-derived dz/dz_lift/need_dz/score fields, which cannot be computed
for an arbitrary CEM-proposed pose without already having executed it)
retains most of the AUC (pooled 0.785 vs 0.811 full-12, Pear unchanged at
0.901/0.903) and IS computable live from a point cloud for any candidate
pose via grasp_6dof/grasp_sampler.py's local_point_density/
normal_consistency/contact_width_ratio functions -- confirmed cheap
(vectorised numpy) via an offline CEM-exploit-risk check
(scripts/geo_ebm_cem_exploit_check.py): CEM-optimised poses landed within
4-10cm of real logged successes in 3/5 held-out scenes, not the
~1.7-std unconstrained-exploit region that killed v1.

Static positives/negatives: read directly from the dataset's own precomputed
6-dim features (real, physically-executed rows -- no live computation
needed). Uniform + hard-mined negatives: sampled (x, y, yaw, width) fed
through a per-object CACHED reference point cloud
(grasp_6dof/dataset/lggsn_object_pointclouds/{obj}.npy, generated by
scripts/cache_object_pointclouds.py) via the same live-feature functions --
an approximation (one point cloud per object, not per-scene) analogous to
the existing v2 code's own use of one mean visual feature per object for
mining conditioning (obj_mean_vis), not a new methodological liberty.

Usage:
  conda run -n tango python train_geo_ebm_grasp.py
  EBM_EPOCHS=50 conda run -n tango python train_geo_ebm_grasp.py   # smoke test
"""
import json
import math
import os

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset

from grasp_6dof.grasp_sampler import rpy_to_R, local_point_density, contact_width_ratio
from tango_robot.env_soarm import TABLE_TOP_Z

JSONL_PATH   = os.environ.get("EBM_JSONL",  "grasp_6dof/dataset/lggsn_candidates_v9.jsonl")
CKPT_PATH    = os.environ.get("EBM_CKPT",   "grasp_6dof/models/geo_ebm_allobj.pt")
PCD_DIR      = "grasp_6dof/dataset/lggsn_object_pointclouds"
OBJECTS      = ["banana", "can", "cracker", "cylinder", "drill", "mustard", "pear"]
N_EPOCHS     = int(os.environ.get("EBM_EPOCHS",    "1000"))
BATCH_SIZE   = int(os.environ.get("EBM_BATCH",     "128"))
LR           = float(os.environ.get("EBM_LR",      "3e-4"))
WEIGHT_DECAY = float(os.environ.get("EBM_WD",      "1e-4"))
K_STATIC     = int(os.environ.get("EBM_K_STATIC",  "4"))
K_UNIFORM    = int(os.environ.get("EBM_K_UNIFORM", "4"))
K_HARD       = int(os.environ.get("EBM_K_HARD",    "4"))
HARD_POP     = int(os.environ.get("EBM_HARD_POP",  "32"))
HARD_ITERS   = int(os.environ.get("EBM_HARD_ITERS", "3"))
VIS_DIM      = 256
GEOM_FEATS   = ["width", "H", "local_point_density", "normal_consistency", "contact_width_ratio", "pe_ik"]
GEOM_DIM     = len(GEOM_FEATS)
IN_DIM       = GEOM_DIM + VIS_DIM

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ── live geometric feature computation (for uniform/hard negatives) ─────────
#
# normal_consistency's real cost is Open3D's per-point normal estimation
# (KD-tree + consistent-orientation propagation) -- NOT the bbox mask/std
# itself. Recomputing that from scratch for every one of the thousands of
# CEM-mining candidates evaluated during training is infeasible (a 10-epoch
# smoke run did not finish in 5 minutes). Fix: estimate normals ONCE per
# object point cloud at cache time (scripts/cache_object_pointclouds.py),
# then here just index into the precomputed per-point normals array for
# whichever points fall in a given candidate's gripper bbox -- the same
# masking math as grasp_6dof/grasp_sampler.py's normal_consistency, just
# reusing a precomputed normals array instead of re-running Open3D.

def live_geom_feats(x: float, y: float, yaw: float, width: float,
                     H: float, pe_ik: float, pcd: np.ndarray,
                     normals: np.ndarray, depth: float = 0.04) -> np.ndarray:
    """Single-candidate version (kept for the offline exploit-check script)."""
    roll, pitch = math.pi, 0.0
    R = rpy_to_R(roll, pitch, float(yaw))
    pos_g = np.array([x, y, TABLE_TOP_Z + 0.02])

    ld = local_point_density(pos_g, R, width, pcd)
    cwr = contact_width_ratio(pos_g, R, width, pcd)

    local = (pcd - pos_g) @ R
    hw, hd = width / 2.0, depth / 2.0
    mask = (
        (np.abs(local[:, 0]) <= hw) &
        (np.abs(local[:, 1]) <= hw) &
        (np.abs(local[:, 2]) <= hd)
    )
    nc = float(np.std(normals[mask, 2])) if mask.sum() >= 5 else 0.0

    return np.array([width, H, ld, nc, cwr, pe_ik], dtype=np.float32)


def live_geom_feats_batch(xs: np.ndarray, ys: np.ndarray, yaws: np.ndarray, widths: np.ndarray,
                           H: float, pe_ik: float, pcd: np.ndarray, normals: np.ndarray,
                           depth: float = 0.04) -> np.ndarray:
    """Vectorised over a whole population P at once -- the (P, M, 3) local-
    frame transform and bbox mask are batched (einsum + broadcasting); only
    the final per-candidate std/percentile reduction over a ragged
    (variable-count) masked subset remains a lightweight Python loop (cheap:
    plain numpy reductions on precomputed arrays, not Open3D calls). This
    replaces calling live_geom_feats() once per candidate in a Python loop,
    which dominated per-epoch cost even after normals were precomputed."""
    P = len(xs)
    roll, pitch = math.pi, 0.0
    R = np.stack([rpy_to_R(roll, pitch, float(yaw)) for yaw in yaws])       # (P,3,3)
    pos_g = np.stack([xs, ys, np.full(P, TABLE_TOP_Z + 0.02)], axis=1)      # (P,3)

    diff = pcd[None, :, :] - pos_g[:, None, :]          # (P,M,3)
    local = np.einsum("pmj,pjk->pmk", diff, R)          # (P,M,3)

    hw = (widths / 2.0)[:, None]                        # (P,1)
    hd = depth / 2.0
    mask = (
        (np.abs(local[:, :, 0]) <= hw) &
        (np.abs(local[:, :, 1]) <= hw) &
        (np.abs(local[:, :, 2]) <= hd)
    )  # (P,M)

    normals_z = normals[:, 2]
    out = np.zeros((P, GEOM_DIM), dtype=np.float32)
    n_pts = mask.sum(axis=1)
    for p in range(P):
        m = mask[p]
        ld = float(n_pts[p]) / pcd.shape[0]
        if n_pts[p] >= 5:
            nc = float(np.std(normals_z[m]))
        else:
            nc = 0.0
        if n_pts[p] >= 10 and widths[p] > 0:
            local_x = local[p, m, 0]
            cwr = float(np.percentile(local_x, 90) - np.percentile(local_x, 10)) / max(1e-6, widths[p])
        else:
            cwr = 0.0
        out[p] = [widths[p], H, ld, nc, cwr, pe_ik]
    return out


# ── 1. Dataset ────────────────────────────────────────────────────────────────

class GeoGraspScoreDataset(Dataset):
    def __init__(self, jsonl_path: str, pcd_dir: str):
        rows = [json.loads(l) for l in open(jsonl_path)]

        geom    = np.array([[r[f] for f in GEOM_FEATS] for r in rows], dtype=np.float32)
        vis_raw = np.array([r["visual_feat"] for r in rows], dtype=np.float32)
        labels  = np.array([r["label"] for r in rows], dtype=np.float32)
        queries = [r["query"] for r in rows]
        xs      = np.array([r["x"] for r in rows], dtype=np.float32)
        ys      = np.array([r["y"] for r in rows], dtype=np.float32)
        yaws    = np.array([r["yaw"] for r in rows], dtype=np.float32)
        widths  = np.array([r["width"] for r in rows], dtype=np.float32)

        self.geom_mean = geom.mean(0)
        self.geom_std  = geom.std(0).clip(min=1e-6)
        geom_norm      = (geom - self.geom_mean) / self.geom_std

        norms    = np.linalg.norm(vis_raw, axis=1, keepdims=True).clip(min=1e-8)
        vis_norm = vis_raw / norms

        self.geom  = torch.from_numpy(geom_norm.astype(np.float32))
        self.vis   = torch.from_numpy(vis_norm.astype(np.float32))
        self.label = labels
        self.queries = queries
        self.N = len(rows)

        # raw (x, y, yaw, width, H, pe_ik) kept per-object for uniform/hard
        # negative sampling bounds (mining explores THIS observed range, not
        # arbitrary far-away poses -- same discipline as v2's xy_norm_lo/hi).
        self.obj_ranges = {}
        for obj in OBJECTS:
            idx = [i for i, q in enumerate(queries) if q == obj]
            if not idx:
                continue
            self.obj_ranges[obj] = dict(
                x_lo=float(xs[idx].min()) - 0.02, x_hi=float(xs[idx].max()) + 0.02,
                y_lo=float(ys[idx].min()) - 0.02, y_hi=float(ys[idx].max()) + 0.02,
                w_lo=float(widths[idx].min()), w_hi=float(widths[idx].max()),
                H=float(geom[idx, GEOM_FEATS.index("H")].mean()),
                pe_ik=float(geom[idx, GEOM_FEATS.index("pe_ik")].mean()),
            )

        by_obj, pos_by_obj, neg_by_obj = {}, {}, {}
        for i, q in enumerate(queries):
            by_obj.setdefault(q, []).append(i)
            (pos_by_obj if labels[i] == 1 else neg_by_obj).setdefault(q, []).append(i)
        print(f"\n[Dataset] {self.N} total rows (label=1 + label=0)")
        print(f"  {'object':<12} {'n_pos':>6} {'n_neg':>6}")
        for obj in OBJECTS:
            print(f"  {obj:<12} {len(pos_by_obj.get(obj, [])):>6} {len(neg_by_obj.get(obj, [])):>6}")
        self._by_obj = by_obj
        self.pos_by_obj = pos_by_obj
        self.neg_by_obj = neg_by_obj
        self.pos_indices = [i for i in range(self.N) if labels[i] == 1]

        # Recentre each cached reference point cloud onto THIS dataset's own
        # observed mean object position (real absolute world coords vary
        # trial-to-trial depending on the caller's own spawn RNG stream --
        # the cached cloud's absolute coordinates are only valid for the one
        # specific replayed scene used to build the cache, not for training
        # rows or later inference trials with a different placement).
        self.pcd = {}
        self.normals = {}
        for obj in OBJECTS:
            npz_path = os.path.join(pcd_dir, f"{obj}.npz")
            if os.path.exists(npz_path) and obj in self.obj_ranges:
                data = np.load(npz_path)
                ref_xy = data["ref_xy"]
                target_x = (self.obj_ranges[obj]["x_lo"] + self.obj_ranges[obj]["x_hi"]) / 2.0
                target_y = (self.obj_ranges[obj]["y_lo"] + self.obj_ranges[obj]["y_hi"]) / 2.0
                shift = np.array([target_x - ref_xy[0], target_y - ref_xy[1], 0.0], dtype=np.float32)
                self.pcd[obj] = data["points"] + shift
                self.normals[obj] = data["normals"]

    def mean_vis(self, obj: str) -> torch.Tensor:
        idx = self._by_obj[obj]
        return self.vis[idx].mean(0)

    def sample_random_geom(self, obj: str, rng: np.random.Generator, n: int) -> np.ndarray:
        """Uniform-random (x,y,yaw,width) within this object's observed range,
        featurised live via its cached reference point cloud."""
        rg = self.obj_ranges[obj]
        pcd = self.pcd.get(obj)
        normals = self.normals.get(obj)
        xs = rng.uniform(rg["x_lo"], rg["x_hi"], size=n)
        ys = rng.uniform(rg["y_lo"], rg["y_hi"], size=n)
        yaws = rng.uniform(-np.pi / 2, np.pi / 2, size=n)
        widths = rng.uniform(rg["w_lo"], rg["w_hi"], size=n)
        out = live_geom_feats_batch(xs, ys, yaws, widths, rg["H"], rg["pe_ik"], pcd, normals)
        return (out - self.geom_mean) / self.geom_std


# ── 2. Energy model (same architecture as v2, just IN_DIM differs) ──────────

class EnergyNet(nn.Module):
    def __init__(self, hidden: int = 256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(IN_DIM, hidden),  nn.SiLU(),
            nn.Linear(hidden, hidden),  nn.SiLU(),
            nn.Linear(hidden, hidden // 2), nn.SiLU(),
            nn.Linear(hidden // 2, 1),
        )

    def forward(self, geom_feat, cond):
        inp = torch.cat([geom_feat, cond], dim=-1)
        return self.net(inp).squeeze(-1)


# ── 3. Hard-negative mining (CEM over (x,y,yaw,width), live-featurised) ─────

def _mine_hard_negatives(model: EnergyNet, cond_vec: torch.Tensor, obj: str,
                          dataset: GeoGraspScoreDataset,
                          rng: np.random.Generator, k: int) -> np.ndarray:
    rg = dataset.obj_ranges[obj]
    pcd = dataset.pcd.get(obj)
    normals = dataset.normals.get(obj)
    dev = cond_vec.device

    pop_x = rng.uniform(rg["x_lo"], rg["x_hi"], size=HARD_POP).astype(np.float32)
    pop_y = rng.uniform(rg["y_lo"], rg["y_hi"], size=HARD_POP).astype(np.float32)
    pop_yaw = rng.uniform(-np.pi / 2, np.pi / 2, size=HARD_POP).astype(np.float32)
    pop_w = rng.uniform(rg["w_lo"], rg["w_hi"], size=HARD_POP).astype(np.float32)

    def featurize(px, py, pyaw, pw):
        feats = live_geom_feats_batch(px, py, pyaw, pw, rg["H"], rg["pe_ik"], pcd, normals)
        return (feats - dataset.geom_mean) / dataset.geom_std

    for _ in range(HARD_ITERS):
        feat = featurize(pop_x, pop_y, pop_yaw, pop_w)
        feat_t = torch.tensor(feat, dtype=torch.float32, device=dev)
        cond_b = cond_vec.unsqueeze(0).expand(HARD_POP, -1)
        with torch.no_grad():
            logits = model(feat_t, cond_b).cpu().numpy()
        elite_n = max(2, HARD_POP // 4)
        elite_idx = np.argsort(-logits)[:elite_n]

        mean_x, std_x = pop_x[elite_idx].mean(), max(0.01, pop_x[elite_idx].std())
        mean_y, std_y = pop_y[elite_idx].mean(), max(0.01, pop_y[elite_idx].std())
        elite_yaw = pop_yaw[elite_idx]
        yaw_mean = float(np.arctan2(np.sin(elite_yaw).mean(), np.cos(elite_yaw).mean()))
        yaw_std = max(0.15, float(elite_yaw.std()))
        mean_w, std_w = pop_w[elite_idx].mean(), max(0.01, pop_w[elite_idx].std())

        pop_x = np.clip(rng.normal(mean_x, std_x, HARD_POP), rg["x_lo"], rg["x_hi"]).astype(np.float32)
        pop_y = np.clip(rng.normal(mean_y, std_y, HARD_POP), rg["y_lo"], rg["y_hi"]).astype(np.float32)
        pop_yaw = np.clip(rng.normal(yaw_mean, yaw_std, HARD_POP), -np.pi / 2, np.pi / 2).astype(np.float32)
        pop_w = np.clip(rng.normal(mean_w, std_w, HARD_POP), rg["w_lo"], rg["w_hi"]).astype(np.float32)

    feat = featurize(pop_x, pop_y, pop_yaw, pop_w)
    feat_t = torch.tensor(feat, dtype=torch.float32, device=dev)
    cond_b = cond_vec.unsqueeze(0).expand(HARD_POP, -1)
    with torch.no_grad():
        logits = model(feat_t, cond_b).cpu().numpy()
    top_idx = np.argsort(-logits)[:k]
    return feat[top_idx]


# ── 4. Training ───────────────────────────────────────────────────────────────

def train(dataset: GeoGraspScoreDataset) -> EnergyNet:
    model = EnergyNet(hidden=256).to(device)
    optim = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(optim, T_max=N_EPOCHS, eta_min=1e-5)
    rng = np.random.default_rng(0)

    n_params = sum(p.numel() for p in model.parameters())
    n_batches = max(1, len(dataset.pos_indices) // BATCH_SIZE)
    print(f"[Train] EnergyNet params: {n_params:,}  device: {device}  IN_DIM={IN_DIM}")
    print(f"[Train] {N_EPOCHS} epochs  batch={BATCH_SIZE}  lr={LR}  wd={WEIGHT_DECAY}  "
          f"pos_anchors={len(dataset.pos_indices)}  batches/epoch={n_batches}")
    print(f"[Train] negatives/positive: {K_STATIC} static + {K_UNIFORM} uniform(live) + "
          f"{K_HARD} hard(live-mined via {HARD_ITERS}-iter CEM, pop={HARD_POP})")

    obj_mean_vis = {obj: dataset.mean_vis(obj).to(device) for obj in OBJECTS if obj in dataset._by_obj}

    best_loss, best_state = float("inf"), None
    pos_indices = np.array(dataset.pos_indices)

    for epoch in range(1, N_EPOCHS + 1):
        model.train()
        rng.shuffle(pos_indices)
        total_loss, total_correct, total_n = 0.0, 0, 0

        for b in range(n_batches):
            batch_idx = pos_indices[b * BATCH_SIZE:(b + 1) * BATCH_SIZE]
            if len(batch_idx) == 0:
                continue
            objs_b = [dataset.queries[i] for i in batch_idx]
            cond_b = dataset.vis[batch_idx].to(device)
            pos_feat = dataset.geom[batch_idx].to(device)
            B = len(batch_idx)

            model.eval()
            hard_by_obj = {}
            uniform_by_obj = {}
            for obj in set(objs_b):
                cv = obj_mean_vis.get(obj, cond_b[0])
                hard_by_obj[obj] = _mine_hard_negatives(model, cv, obj, dataset, rng, K_HARD)
                uniform_by_obj[obj] = dataset.sample_random_geom(obj, rng, K_UNIFORM)
            model.train()

            neg_feats = np.zeros((B, K_STATIC + K_UNIFORM + K_HARD, GEOM_DIM), dtype=np.float32)
            for i, obj in enumerate(objs_b):
                neg_pool = dataset.neg_by_obj.get(obj) or list(range(dataset.N))
                static_idx = rng.choice(neg_pool, size=K_STATIC, replace=len(neg_pool) < K_STATIC)
                neg_feats[i, :K_STATIC] = dataset.geom[static_idx].numpy()
                neg_feats[i, K_STATIC:K_STATIC + K_UNIFORM] = uniform_by_obj[obj]
                neg_feats[i, K_STATIC + K_UNIFORM:] = hard_by_obj[obj]

            K_total = K_STATIC + K_UNIFORM + K_HARD
            neg_feats_t = torch.tensor(neg_feats, dtype=torch.float32, device=device)
            cond_exp = cond_b.unsqueeze(1).expand(B, K_total, VIS_DIM).reshape(B * K_total, VIS_DIM)
            neg_flat = neg_feats_t.reshape(B * K_total, GEOM_DIM)
            neg_logit = model(neg_flat, cond_exp).reshape(B, K_total)
            pos_logit = model(pos_feat, cond_b)

            logits_all = torch.cat([pos_logit.unsqueeze(1), neg_logit], dim=1)
            target = torch.zeros(B, dtype=torch.long, device=device)
            loss = F.cross_entropy(logits_all, target)

            optim.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optim.step()

            total_loss += loss.item() * B
            total_correct += (logits_all.argmax(dim=1) == 0).sum().item()
            total_n += B

        sched.step()
        avg_loss = total_loss / max(1, total_n)
        acc = total_correct / max(1, total_n)

        if avg_loss < best_loss:
            best_loss = avg_loss
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}

        if epoch % 20 == 0 or epoch == 1:
            print(f"  epoch {epoch:4d}/{N_EPOCHS}  loss={avg_loss:.5f}  "
                  f"positive-ranked-top1_acc={acc:.3f}  best_loss={best_loss:.5f}")

    os.makedirs(os.path.dirname(CKPT_PATH) or ".", exist_ok=True)
    torch.save(best_state, CKPT_PATH)
    print(f"[Train] Best loss: {best_loss:.5f}  -> {CKPT_PATH}")
    model.load_state_dict(best_state)
    return model


def save_inference_stats(dataset: GeoGraspScoreDataset, ckpt_path: str):
    stats = {
        "geom_mean": dataset.geom_mean.tolist(),
        "geom_std": dataset.geom_std.tolist(),
        "geom_feats": GEOM_FEATS,
        "obj_ranges": dataset.obj_ranges,
        "mean_vis_per_obj": {
            obj: dataset.vis[idx].mean(0).numpy().tolist()
            for obj, idx in dataset._by_obj.items()
        },
    }
    stats_path = ckpt_path.replace(".pt", "_stats.json")
    with open(stats_path, "w") as f:
        json.dump(stats, f)
    print(f"[Stats] Saved -> {stats_path}")


def main():
    dataset = GeoGraspScoreDataset(JSONL_PATH, PCD_DIR)
    model = train(dataset)
    save_inference_stats(dataset, CKPT_PATH)


if __name__ == "__main__":
    main()
