#!/usr/bin/env python
"""Phase 4: LaTeX table generation from Phase 3's already-computed pairwise
comparison records.

Pure stdlib -- no matplotlib dependency (see figures.py for the PNG/PDF
plots, which do need it and therefore run differently -- see that module's
docstring). This module never recomputes a statistic; every number it
emits is read verbatim from research_agent_pilots/lggsn_analysis/outputs/
pairwise_comparisons.json (real_analysis.py's already-tested output), only
formatted differently. Output is deterministic pure string formatting --
two calls on the same input always produce byte-identical LaTeX.

These are standalone .tex snippets meant to be \\input{} from a paper, not
edits to any existing paper file -- research_agent_pilots/lggsn_analysis/
never touches paper_final.tex or any other paper file.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Mapping, Sequence

_LATEX_ESCAPES: dict[str, str] = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
    "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    "\\": r"\textbackslash{}",
}


def escape_latex(text: str) -> str:
    return "".join(_LATEX_ESCAPES.get(ch, ch) for ch in str(text))


def _fmt(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.4f}"
    return str(value)


_P_VALUE_DISPLAY_FLOOR = 0.0001


def _fmt_p(value: float) -> str:
    """p-values below the display floor are shown as '<0.0001', never
    rounded to '0.0000' -- rounding a genuinely tiny but nonzero p-value to
    display as exactly zero would misrepresent it as impossible rather
    than merely small."""
    if value < _P_VALUE_DISPLAY_FLOOR:
        return f"$<${_P_VALUE_DISPLAY_FLOOR:.4f}"
    return f"{value:.4f}"


def render_pairwise_summary_table(comparisons: Sequence[Mapping[str, Any]]) -> str:
    lines: list[str] = [
        r"% Auto-generated by research_agent_pilots/lggsn_analysis/latex_tables.py",
        r"% Source: research_agent_pilots/lggsn_analysis/outputs/pairwise_comparisons.json",
        r"% Every number is read verbatim from real_analysis.py's tested output -- never",
        r"% recomputed or independently rounded here.",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{LGGSN core-matrix pairwise comparisons (582 aligned pairs each; exact "
        r"McNemar test; Holm-Bonferroni-adjusted jointly across all five comparisons; "
        r"$\alpha=0.05$, predeclared).}",
        r"  \label{tab:lggsn-pairwise}",
        r"  \begin{tabular}{llrrrrrrl}",
        r"    \toprule",
        r"    A & B & Acc(A) & Acc(B) & Diff(B$-$A) & $p$ (raw) & $p$ (Holm) & 95\% CI & Result \\",
        r"    \midrule",
    ]
    for c in comparisons:
        ci = c["bootstrap"]
        lines.append(
            f"    {escape_latex(c['checkpoint_a'])} & {escape_latex(c['checkpoint_b'])} & "
            f"{_fmt(c['accuracy_a'])} & {_fmt(c['accuracy_b'])} & {_fmt(c['accuracy_diff_b_minus_a'])} & "
            f"{_fmt_p(c['mcnemar_p_value_raw'])} & {_fmt_p(c['mcnemar_p_value_holm_adjusted'])} & "
            f"[{_fmt(ci['ci_lower'])}, {_fmt(ci['ci_upper'])}] & "
            f"{escape_latex(c['interpretation_holm'])} \\\\"
        )
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def render_per_query_table(comparisons: Sequence[Mapping[str, Any]]) -> str:
    lines: list[str] = [
        r"% Auto-generated by research_agent_pilots/lggsn_analysis/latex_tables.py",
        r"% Source: research_agent_pilots/lggsn_analysis/outputs/per_query_breakdown.csv",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Per-query pair-accuracy breakdown for each LGGSN core-matrix comparison.}",
        r"  \label{tab:lggsn-per-query}",
        r"  \begin{tabular}{llrrrrr}",
        r"    \toprule",
        r"    A & B & Query & $n$ & Acc(A) & Acc(B) & Diff(B$-$A) \\",
        r"    \midrule",
    ]
    for c in comparisons:
        for row in c["per_query_breakdown"]:
            lines.append(
                f"    {escape_latex(c['checkpoint_a'])} & {escape_latex(c['checkpoint_b'])} & "
                f"{escape_latex(row['query'])} & {row['n_pairs']} & {_fmt(row['accuracy_a'])} & "
                f"{_fmt(row['accuracy_b'])} & {_fmt(row['accuracy_diff_b_minus_a'])} \\\\"
            )
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def write_pairwise_summary_tex(comparisons: Sequence[Mapping[str, Any]], path: Path) -> None:
    with Path(path).open("w", encoding="utf-8", newline="\n") as f:
        f.write(render_pairwise_summary_table(comparisons))


def write_per_query_tex(comparisons: Sequence[Mapping[str, Any]], path: Path) -> None:
    with Path(path).open("w", encoding="utf-8", newline="\n") as f:
        f.write(render_per_query_table(comparisons))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--comparisons-json", required=True)
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args(argv)

    comparisons = json.loads(Path(args.comparisons_json).read_text(encoding="utf-8"))["comparisons"]
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    write_pairwise_summary_tex(comparisons, output_dir / "pairwise_summary.tex")
    write_per_query_tex(comparisons, output_dir / "per_query_breakdown.tex")

    print(f"[lggsn_latex_tables] wrote 2 tables to {output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
