"""
Ensemble-size-matched IK-margin vs consensus comparison, for
Pear / MustardBottle / CrackerBox / TomatoSoupCan.

TomatoSoupCan added 2026-07-09 (run_ikmargin_n10_tomatosoupcan.sh +
run_consensus_n10_tomatosoupcan.sh) to close a gap: the paper's "Reliability
across generation seeds" paragraph names Pear AND TomatoSoupCan as objects
where OT-CFM is less reliable across seeds than CFM-noOT/DDPM, but this
ikmargin-vs-consensus mitigation check previously only covered Pear.

This is the controlled counterpart to run_ikmargin_vs_consensus.py: that
script compared ikmargin(pool=10) against consensus(pool=5), an ensemble-size
confound found after the fact. Here both strategies use pool size 10
(ikmargin_*.jsonl's existing --ikmargin-n 10 data, and a fresh
--consensus-n 10 re-run in phase1_matched_n10/, generated by
scripts/run_consensus_n10_matched.sh on the identical (object, orient_seed,
ensemble_base) grid), so any difference found here is attributable to the
selection rule itself, not pool size.

Each object's two samples are independent (no shared candidate pool /
seed reuse between the two strategies), so Fisher's exact test on the 2x2
success/fail table is used, same as the original (confounded) script.

Output: paperA_data/formal_results/ikmargin_vs_consensus_matched_n10.csv
"""
import csv
import json
from pathlib import Path

from scipy.stats import fisher_exact

BASE = Path(__file__).resolve().parent.parent

OBJECTS = ["Pear", "MustardBottle", "CrackerBox", "TomatoSoupCan"]


def load(path):
    return [json.loads(l) for l in open(path)]


def counts(rows):
    s = sum(1 for r in rows if r["success"] == "true")
    return s, len(rows) - s, len(rows)


def main():
    out_rows = []
    for obj in OBJECTS:
        ik_rows = load(BASE / f"phase1_v2/ikmargin_{obj}.jsonl")
        co_rows = load(BASE / f"phase1_matched_n10/consensus_n10_{obj}.jsonl")

        ik_s, ik_f, ik_n = counts(ik_rows)
        co_s, co_f, co_n = counts(co_rows)

        table = [[ik_s, ik_f], [co_s, co_f]]
        odds_ratio, p = fisher_exact(table, alternative="two-sided")

        out_rows.append({
            "object": obj,
            "ikmargin_ensemble_n": 10,
            "ikmargin_success": ik_s,
            "ikmargin_n": ik_n,
            "ikmargin_rate": round(ik_s / ik_n, 4),
            "consensus_ensemble_n": 10,
            "consensus_success": co_s,
            "consensus_n": co_n,
            "consensus_rate": round(co_s / co_n, 4),
            "rate_diff_ikmargin_minus_consensus": round(ik_s / ik_n - co_s / co_n, 4),
            "fisher_exact_odds_ratio": round(odds_ratio, 4),
            "fisher_exact_p": p,
            "note": "ensemble sizes matched (10 vs 10) -- controlled test of selection rule alone",
        })

    out_path = BASE / "formal_results/ikmargin_vs_consensus_matched_n10.csv"
    out_path.parent.mkdir(exist_ok=True)
    with open(out_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(out_rows[0].keys()))
        w.writeheader()
        w.writerows(out_rows)
    print(f"wrote {len(out_rows)} rows to {out_path}")


if __name__ == "__main__":
    main()
