"""
Extends run_contact_features_stats.py's 3-object (Pear/MustardBottle/CrackerBox)
analysis to 6 objects, adding TomatoSoupCan/PowerDrill/Scissors (phase0_diag_extended/
data_with_contact_feats_new3.json, generated by run_phase0_2_extended_analysis.py).
Same Mann-Whitney + rank-biserial + Bonferroni + Benjamini-Hochberg procedure as
the original, just over 18 tests (3 features x 6 objects) instead of 9.

Known data quality note (not a bug -- see grasp_sampler.py's own docstring on
normal_consistency: "Low -> flat surface (scissors failure)"): Scissors is thin/
flat, and all three contact features are exactly 0.0 for all 50 of its trials
(gripper bbox catches ~0 points on a thin object). This is a structural floor
effect of the feature *design* for thin-object geometries, not sampling noise --
Mann-Whitney against two identical-zero groups is degenerate (scipy returns
p=1.0). Scissors rows are kept in the table for transparency but should be read
as "this feature set cannot discriminate for this object shape", not as
evidence there is no exploitable signal for Scissors by any method.

Output: paperA_data/formal_results/contact_features_bonferroni_bh_6obj.csv
"""
import csv
import json
from pathlib import Path

import numpy as np
from scipy.stats import mannwhitneyu, false_discovery_control

BASE = Path(__file__).resolve().parent.parent

OBJECTS = [
    ("Pear", BASE / "phase0_diag/data_with_contact_feats.json"),
    ("MustardBottle", BASE / "phase0_diag/data_with_contact_feats.json"),
    ("CrackerBox", BASE / "phase0_diag/data_with_contact_feats.json"),
    ("TomatoSoupCan", BASE / "phase0_diag_extended/data_with_contact_feats_new3.json"),
    ("PowerDrill", BASE / "phase0_diag_extended/data_with_contact_feats_new3.json"),
    ("Scissors", BASE / "phase0_diag_extended/data_with_contact_feats_new3.json"),
]
FEATURES = ["local_point_density", "normal_consistency", "contact_width_ratio"]


def main():
    cache = {}
    rows = []
    for obj, path in OBJECTS:
        if path not in cache:
            cache[path] = json.load(open(path))
        d = cache[path]
        obj_data = [x for x in d if x["object"] == obj]
        succ = [x for x in obj_data if x["success"]]
        fail = [x for x in obj_data if not x["success"]]
        for feat in FEATURES:
            s = np.array([x[feat] for x in succ])
            f = np.array([x[feat] for x in fail])
            degenerate = np.all(s == s[0]) and np.all(f == f[0]) and (len(set(s.tolist() + f.tolist())) <= 1)
            if degenerate:
                u, p, rank_biserial = float("nan"), 1.0, 0.0
            else:
                u, p = mannwhitneyu(s, f, alternative="two-sided")
                rank_biserial = 1 - 2 * u / (len(s) * len(f))
            rows.append({
                "object": obj,
                "feature": feat,
                "n_succ": len(s),
                "n_fail": len(f),
                "succ_mean": round(float(s.mean()), 5),
                "succ_std": round(float(s.std()), 5),
                "fail_mean": round(float(f.mean()), 5),
                "fail_std": round(float(f.std()), 5),
                "mannwhitney_U": u,
                "p_raw": p,
                "rank_biserial_effect_size": round(rank_biserial, 4),
                "degenerate_all_zero": degenerate,
            })

    n_tests = len(rows)
    alpha = 0.05
    bonf_alpha = alpha / n_tests
    p_raw = np.array([r["p_raw"] for r in rows])
    p_bh = false_discovery_control(p_raw, method="bh")

    for i, r in enumerate(rows):
        r["bonferroni_alpha"] = round(bonf_alpha, 6)
        r["sig_bonferroni"] = "SIG" if r["p_raw"] < bonf_alpha else "ns"
        r["p_bh_adjusted"] = round(float(p_bh[i]), 6)
        r["sig_bh_0.05"] = "SIG" if p_bh[i] < alpha else "ns"

    rows.sort(key=lambda r: r["p_raw"])

    out_path = BASE / "formal_results/contact_features_bonferroni_bh_6obj.csv"
    out_path.parent.mkdir(exist_ok=True)
    with open(out_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {len(rows)} rows ({n_tests} tests, Bonferroni alpha={bonf_alpha:.5f}) to {out_path}")


if __name__ == "__main__":
    main()
